#!/bin/bash
#
# lddsafe - Safely print shared library dependencies (similar to ldd).
# Author: Ricardo Garcia Gonzalez.
# Author: Ivan Mironov.
# License: Public domain code.
#

# Better for grep and expected output of other tools.
export LANG=C

# Print error and exit.
die()
{
	echo "ERROR: $1" 1>&2
	exit 1
}

# Find required program.
findexec()
{
	which "$1" || die "$1 not found"
}

# Check file exists and is executable.
checkexec()
{
	[ -x "$1" ] || die "$1 missing or not executable"
}

# Check file exists and is readable.
checkreadable()
{
	[ -r "$1" ] || die "$1 missing or not readable"
}

# Check for bash version.
[ -n "$BASH_VERSION" ] || die "Bash required"
[ ${BASH_VERSINFO[0]} -ge 4 ] || die "Bash version 4 or later required"

# Check needed programs.
findexec which >/dev/null
OBJDUMP=$( findexec objdump )
CAT=$( findexec cat )
TR=$( findexec tr )
SED=$( findexec sed )

# Check needed files.
checkreadable /etc/ld.so.conf

# Check arguments.
if [ "$1" == "-n" ]; then
	recursive=0
	shift
else
	recursive=1
fi
if [ $# -eq 0 ]; then
	echo "Usage: $( basename $0 ) [-n] FILE..." 2>&1
	exit 1
fi
for arg in "$@"; do
	checkexec "$1"
done

# Library directories.
libdirs="$( echo /lib /lib64 /usr/lib /usr/lib64 && \
	    $CAT /etc/ld.so.conf && \
	    $TR : ' ' <<<$LD_LIBRARY_PATH )"

# Search for a given library name.
searchlib()
{
	found=0
	for libdir in $libdirs; do
		path="$libdir"/"$1"
		if [ -x "$path" ]; then
			found=1
			break
		fi
	done
	[ $found -eq 1 ] && echo "$path"
}

# Already visited libraries.
declare -A visitedlibs

# Print dependency results, recursively.
recursivedeps()
{
	for lib in $( $OBJDUMP -p "$1" | \
			$SED -n 's,^ *NEEDED \+\([^ ]\+\) *$,\1,p' ); do
		if [ ! "${visitedlibs[$lib]}" ]; then
			visitedlibs["$lib"]=1
			file=`searchlib "$lib"`
			if [ "$file" ]; then
				echo "	$lib => $file"
				[ $recursive -eq 1 ] && recursivedeps "$file"
			else
				echo "	$lib => not found"
			fi
		fi
	done
}

# Search symbol names in library directories.
for arg in "$@"; do
	# Print file name when more than one file given.
	[ $# -gt 1 ] && echo "${arg}:"

	# Get a unique list of library dependencies for this argument.
	unset visitedlibs
	declare -A visitedlibs
	recursivedeps "$arg"
done
exit 0
